#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import agent
import sys
from custom_certificate_manager import list_custom_certificates

api_path = os.environ["API_PATH"]

data = json.load(sys.stdin)

json.dump(certificates, fp=sys.stdout)
