#!/bin/bash

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

# The "traefik1" instance was installed when VPN IP address was undefined,
# before the "create-cluster" action run. Here we replace the fallback
# value 127.0.0.1 with the correct VPN IP address, to fix Prometheus
# scrape endpoint configuration.

if [[ ${MODULE_ID} == traefik1 ]] &&
    redis-exec hget module/traefik1/metrics_targets traefik | grep -q -F 127.0.0.1 ; then
    # Run at most one time:
    exec ../actions/create-module/80provision_metrics
fi
