#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import os
import sys
import re

evdata = json.load(sys.stdin)
if os.environ['NODE_ID'] != str(evdata['node']):
    sys.exit(0) # module was on another node

# Remove .yml files under configs/ that match the module_id of the removed
# module.

module_id = evdata["module"]
module_pattern = re.compile('(?<![A-Za-z0-9])' + re.escape(module_id) + '(?![A-Za-z0-9])')

for dentry in os.scandir('configs'):
    if not dentry.is_file(follow_symlinks=False):
        continue
    if not dentry.name.endswith('.yml'):
        continue
    if module_pattern.search(dentry.name):
        try:
            os.unlink(dentry.path)
            print(f"Removed {dentry.path}", file=sys.stderr)
        except FileNotFoundError:
            pass
