#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import agent
import cert_helpers

agent.set_weight(os.path.basename(__file__), 0) # Validation step, no task progress at all

def main():
    request = json.load(sys.stdin)
    http_route_names = cert_helpers.read_names_of_automatic_http_routes()
    if request.get('check_routes', False) and request['fqdn'].lower() in http_route_names:
        agent.set_status('validation-failed')
        json.dump([{'field':'fqdn','parameter':'fqdn','value': request['fqdn'],'error':'fqdn_conflicts_with_route'}], fp=sys.stdout)
        sys.exit(2)

if __name__ == "__main__":
    main()
