#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import os
import yaml
import cert_helpers

request = json.load(sys.stdin)
cert_helpers.add_default_certificate_name(request['fqdn'])
if request.get('sync'):
    kwargs = {
        'timeout': request.get('sync_timeout', 120),
    }
    obtained = cert_helpers.wait_acmejson_sync(**kwargs)
else:
    obtained = False
json.dump({"obtained": obtained}, fp=sys.stdout)
if request.get('sync') is not None and obtained is False:
    exit(2)
